###
GET http://localhost:8080/api/v1/users?type=PRIVATE

###
GET http://localhost:8080/api/v1/users?type=CORPORATE


###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "Jorge",
  "email": "jcorderop@mail.com",
  "userType": "PRIVATE"
}

###
DELETE http://localhost:8080/api/v1/users/2


###
# curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
POST https://hooks.slack.com/services/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
Content-Type: application/json

{
  "text": "I am going to deploy something"
}

###

