name: Java Spring Boot - Maven -CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  POSTGRESQL_VERSION: 14.2-alpine
  POSTGRESQL_DB: fullstack-db
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: secret
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.2-alpine
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17 - Spring Boots
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run:  mvn -B clean package -P build-frontend --file pom.xml
